# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock_syntax',
            new_name='stock_quote',
        ),
    ]
