# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180525_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprice',
            name='date_time',
        ),
        migrations.AddField(
            model_name='stockprice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
